<?php

/**
 * Authentication and administration helpers for application API clients.
 *
 * API client secrets are generated by OSIRIS, shown once, and stored only as
 * password hashes. A client must be enabled, unexpired, allowed to use the
 * requested API surface, and have every required scope.
 */
class ApiClient
{
    public const SURFACES = ['api', 'mcp'];

    public const SCOPES = [
        'activities.read',
        'activities.write',
        'catalogs.read',
        'dashboards.read',
        'events.read',
        'infrastructures.read',
        'journals.read',
        'organizations.read',
        'persons.read',
        'projects.read',
        'reviews.read',
        'teaching.read',
    ];

    private $collection;

    public function __construct($database = null)
    {
        if ($database === null) {
            $DB = new DB();
            $database = $DB->db;
        }
        $this->collection = $database->apiClients;
    }

    public static function requestClientId(): string
    {
        return trim((string) ($_SERVER['HTTP_X_OSIRIS_CLIENT_ID'] ?? ''));
    }

    public static function requestSecret(?string $fallback = null): string
    {
        $authorization = $_SERVER['HTTP_AUTHORIZATION']
            ?? $_SERVER['REDIRECT_HTTP_AUTHORIZATION']
            ?? '';
        if (preg_match('/^Bearer\s+(.+)$/i', trim((string) $authorization), $matches)) {
            return trim($matches[1]);
        }
        if (!empty($_SERVER['HTTP_X_API_KEY'])) {
            return trim((string) $_SERVER['HTTP_X_API_KEY']);
        }
        return trim((string) ($fallback ?? ''));
    }

    public static function generateClientId(): string
    {
        return 'osc_' . bin2hex(random_bytes(8));
    }

    public static function generateSecret(): string
    {
        return 'osk_' . rtrim(strtr(base64_encode(random_bytes(32)), '+/', '-_'), '=');
    }

    public static function filterSurfaces($values): array
    {
        $values = is_array($values) ? $values : [];
        return array_values(array_intersect(self::SURFACES, array_unique($values)));
    }

    public static function filterScopes($values): array
    {
        $values = is_array($values) ? $values : [];
        return array_values(array_intersect(self::SCOPES, array_unique($values)));
    }

    public function create(
        string $name,
        string $description,
        array $surfaces,
        array $scopes,
        ?string $expiresAt,
        string $createdBy
    ): array {
        $clientId = self::generateClientId();
        $secret = self::generateSecret();
        $this->collection->createIndex(['client_id' => 1], ['unique' => true]);
        $this->collection->insertOne([
            'client_id' => $clientId,
            'name' => $name,
            'description' => $description !== '' ? $description : null,
            'enabled' => true,
            'key_hash' => password_hash($secret, PASSWORD_DEFAULT),
            'key_hint' => substr($secret, -4),
            'surfaces' => self::filterSurfaces($surfaces),
            'scopes' => self::filterScopes($scopes),
            'expires_at' => $expiresAt,
            'created_at' => date('Y-m-d H:i:s'),
            'created_by' => $createdBy,
            'last_used_at' => null,
        ]);
        return ['client_id' => $clientId, 'secret' => $secret];
    }

    public function authenticate(string $surface, array $requiredScopes = [], ?string $fallbackKey = null): bool
    {
        if (!in_array($surface, self::SURFACES, true)) {
            return false;
        }
        $requiredScopes = array_values(array_unique($requiredScopes));
        if (count(self::filterScopes($requiredScopes)) !== count($requiredScopes)) {
            return false;
        }
        $clientId = self::requestClientId();
        $secret = self::requestSecret($fallbackKey);
        if ($clientId === '' || $secret === '') {
            return false;
        }

        $client = $this->collection->findOne(['client_id' => $clientId]);
        if (empty($client) || ($client['enabled'] ?? false) !== true) {
            return false;
        }
        $expiresAt = $client['expires_at'] ?? null;
        if (!empty($expiresAt) && $expiresAt < date('Y-m-d')) {
            return false;
        }
        if (empty($client['key_hash']) || !password_verify($secret, $client['key_hash'])) {
            return false;
        }

        $surfaces = DB::doc2Arr($client['surfaces'] ?? []);
        if (!in_array($surface, $surfaces, true)) {
            return false;
        }
        $scopes = DB::doc2Arr($client['scopes'] ?? []);
        foreach ($requiredScopes as $requiredScope) {
            if (!in_array($requiredScope, $scopes, true)) {
                return false;
            }
        }

        $this->collection->updateOne(
            ['_id' => $client['_id']],
            ['$set' => ['last_used_at' => date('Y-m-d H:i:s')]]
        );
        $GLOBALS['API_CLIENT'] = [
            'client_id' => $clientId,
            'name' => $client['name'] ?? $clientId,
            'surface' => $surface,
            'scopes' => $scopes,
        ];
        return true;
    }

    public function rotate(string $clientId): ?string
    {
        $secret = self::generateSecret();
        $result = $this->collection->updateOne(
            ['client_id' => $clientId],
            ['$set' => [
                'key_hash' => password_hash($secret, PASSWORD_DEFAULT),
                'key_hint' => substr($secret, -4),
                'rotated_at' => date('Y-m-d H:i:s'),
                'rotated_by' => $_SESSION['username'] ?? null,
            ]]
        );
        return $result->getMatchedCount() > 0 ? $secret : null;
    }
}
